services: docker
language: bash
addons:
  apt:
    packages:
      - pass

env:
  - BASE_ARCH=x86_64
  - BASE_ARCH=aarch64
  - BASE_ARCH=armhf
  - BASE_ARCH=armel
  - BASE_ARCH=i686
  - BASE_ARCH=ppc64le
  - BASE_ARCH=s390x
  - BASE_ARCH=mips
  - BASE_ARCH=mips64el

matrix:
#  fast_finish: true
  allow_failures:
    - env: BASE_ARCH=aarch64
    - env: BASE_ARCH=armhf
    - env: BASE_ARCH=armel
    - env: BASE_ARCH=ppc64le
    - env: BASE_ARCH=s390x
    - env: BASE_ARCH=mips
    - env: BASE_ARCH=mips64el

script: ./run.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./run.sh -d
    on:
      repo: umarcor/qus
      branch: master
  - provider: releases
    skip_cleanup: true
#    api_key:
#      secure:
#    file: "*.tgz"
#    file_glob: true
#    on:
#      repo: umarcor/qus
#      branch: master
#      tags: true
