os: linux
dist: xenial
services: docker
language: minimal
before_install:
  - curl -fsSL https://get.docker.com | sudo sh
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
install: skip
script: ./test.sh

env:
  - QUS_JOB=
  - QUS_JOB=f
  - QUS_JOB=F
  - QUS_JOB=c
  - QUS_JOB=C
  - QUS_JOB=v
  - QUS_JOB=V
  - QUS_JOB=i
  - QUS_JOB=I
  - QUS_JOB=d
  - QUS_JOB=D
  - QUS_JOB=r
  - QUS_JOB=R
  - QUS_JOB=s
  - QUS_JOB=n
  - QUS_JOB=h
  - QUS_JOB=H

stages:
  - build
  - test

jobs:
  fast_finish: true
  allow_failures:
    - env: QUS_JOB=h
    - env: QUS_JOB=H
