os: linux
dist: xenial
services: docker
language: minimal
install: skip

stages:
  - build
  - manifests
  - publish
  - test

script: ./run.sh

env:
  - QUS_JOB=
  - QUS_JOB=f
  - QUS_JOB=F
  - QUS_JOB=c
  - QUS_JOB=C
  - QUS_JOB=v
  - QUS_JOB=V
  - QUS_JOB=i
  - QUS_JOB=I
  - QUS_JOB=d
  - QUS_JOB=D
  - QUS_JOB=r
  - QUS_JOB=R
  - QUS_JOB=s
  - QUS_JOB=n
  - QUS_JOB=h
  - QUS_JOB=H

jobs:
  fast_finish: true
  allow_failures:
    - env: BUILD=fedora
    - env: QUS_JOB=h
    - env: QUS_JOB=H
  include:
    - &build
      stage: build
      env: BUILD=debian
      script: ./run.sh -a
      deploy:
        - &script
          provider: script
          skip_cleanup: true
          script: ./run.sh -d
          on: &on
            repo: dbhi/qus
            branch: master
        - &releases
          provider: releases
          api_key:
            secure: DFvuc1OE3AJ+6Rieoh8Ybhxv/GZlaAc5JNMxY7CWdC0jXmZsxDjM6EU4yVyB9OHvXgXTMomvf3jUq4VbC1CNtt9pMl8xhDPrbrXDEVR0/BxLRhGPmtT5tvS31+QIHK3W0jowmySvhpKLGjqFVuLGLv1ibsHqdJEZUdNTarwtnvZrPeWUBeet/1S2M/aJPeGW2TZWFEMuNakNGO/esRTqcBADDEB29pD4Ou1wNFx0LCxxp3KYF3EXD3p/qXFeFyvH4vcxWJG0jF9vCuNr9Ci9qJJG3RK+0yYoCdcdS2UkX1MAXbMM1nKpMDZSu+mTT0UJh7XuV+8yXh1BugR68dfxj4y6A3Bl3CF2JV7qI3et5P+qtXDmMnbLkAKCUYSOFCpYcSNrvIi1pG7ZdvIQAU8GjkZnptEdfBm3xA+20TMKmRDC1jHNPtzRoh8XgUM1O0IXWzN7v9p7HZ945AAtpEuo/BaErxHXb/lMBWSi4g1xFZWNw1s6PB1QOJfSgyMgIlUEThq/oV3WxL1AfxONsZdEeaq6OLgj++3cfX9njG74cDAhCP70/9KQ2YH/fE4xgBr4QNL2JprhgIX7MTQ0WsSLHXKsZ75FtD3Pcw+5X/5wnr6d+qkUPwJnnF/XDanseXGLiX8oUg4KNdfl2dv+f5rjGo+Kh5qO8KDBVXpJu5m2p6k=
          skip_cleanup: true
          file: "./releases/*.tgz"
          file_glob: true
          draft: true
          on:
            <<: *on
            tags: true
    - <<: *build
      env: BUILD=fedora
      install: sudo apt-get install -y rpm2cpio zstd cpio curl
    - stage: manifests
      env: MANIFESTS
      script: skip
      deploy:
        - <<: *script
          script: ./run.sh -m
    - stage: publish
      if: tag IS present
      env: PUBLISH=
      script: ./run.sh -p
      deploy:
        <<: *releases
        file:
          - test-aarch64
          - test-riscv64
        draft: false
