os: linux
dist: xenial
services: docker
language: minimal
before_install:
  - curl -fsSL https://get.docker.com | sudo sh
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
install: skip
script: ./run.sh

env:
  - QUS_JOB=
  - QUS_JOB=f
  - QUS_JOB=F
  - QUS_JOB=c
  - QUS_JOB=C
  - QUS_JOB=v
  - QUS_JOB=V
  - QUS_JOB=i
  - QUS_JOB=I
  - QUS_JOB=d
  - QUS_JOB=D
  - QUS_JOB=r
  - QUS_JOB=R
  - QUS_JOB=s
  - QUS_JOB=n
  - QUS_JOB=h
  - QUS_JOB=H

stages:
  - build
  - test

jobs:
  fast_finish: true
  allow_failures:
    - env: QUS_JOB=h
    - env: QUS_JOB=H
  include:
    - stage: build
      if: tag IS present
      env: BUILD=debian
      script:
        - ./run.sh -a
        - ./run.sh -p
      deploy:
        - provider: releases
          api_key:
            secure: DFvuc1OE3AJ+6Rieoh8Ybhxv/GZlaAc5JNMxY7CWdC0jXmZsxDjM6EU4yVyB9OHvXgXTMomvf3jUq4VbC1CNtt9pMl8xhDPrbrXDEVR0/BxLRhGPmtT5tvS31+QIHK3W0jowmySvhpKLGjqFVuLGLv1ibsHqdJEZUdNTarwtnvZrPeWUBeet/1S2M/aJPeGW2TZWFEMuNakNGO/esRTqcBADDEB29pD4Ou1wNFx0LCxxp3KYF3EXD3p/qXFeFyvH4vcxWJG0jF9vCuNr9Ci9qJJG3RK+0yYoCdcdS2UkX1MAXbMM1nKpMDZSu+mTT0UJh7XuV+8yXh1BugR68dfxj4y6A3Bl3CF2JV7qI3et5P+qtXDmMnbLkAKCUYSOFCpYcSNrvIi1pG7ZdvIQAU8GjkZnptEdfBm3xA+20TMKmRDC1jHNPtzRoh8XgUM1O0IXWzN7v9p7HZ945AAtpEuo/BaErxHXb/lMBWSi4g1xFZWNw1s6PB1QOJfSgyMgIlUEThq/oV3WxL1AfxONsZdEeaq6OLgj++3cfX9njG74cDAhCP70/9KQ2YH/fE4xgBr4QNL2JprhgIX7MTQ0WsSLHXKsZ75FtD3Pcw+5X/5wnr6d+qkUPwJnnF/XDanseXGLiX8oUg4KNdfl2dv+f5rjGo+Kh5qO8KDBVXpJu5m2p6k=
          skip_cleanup: true
          file:
            - "./releases/*.tgz"
            - test-aarch64
            - test-riscv64
          file_glob: true
          draft: true
          on:
            repo: dbhi/qus
            tags: true
