name: 'push'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

jobs:


  Images:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        src:
          - debian
          - fedora
        arch:
          - x86_64
          - i686
          - aarch64
          - ppc64le
          - s390x
          - armv7hl
          - armhf
          - armel
          - mipsel
          - mips64el
        exclude:
          - src: debian
            arch: armv7hl
          - src: fedora
            arch: armhf
          - src: fedora
            arch: armel
          - src: fedora
            arch: mipsel
          - src: fedora
            arch: mips64el
    name: 'I: ${{ matrix.src }} · ${{ matrix.arch }}'
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies for extracting rpms
      run: sudo apt-get install -y rpm2cpio zstd cpio curl
      if: matrix.src == 'fedora'

    - uses: actions/checkout@v2

    - run: BUILD=${{ matrix.src }} ./run.sh -b
      env:
        BASE_ARCH: ${{ matrix.arch }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/qus'
      run: docker push aptman/qus


  Manifests:
    if: github.event_name != 'pull_request' && github.repository == 'dbhi/qus'
    needs: Images
    runs-on: ubuntu-latest
    steps:

    - name: Enable Docker experimental
      shell: python3 {0}
      run: |
        from pathlib import Path
        from json import load, dump
        with (Path.home() / ".docker" / "config.json").open("r+") as cfg:
            data = load(cfg)
            data['experimental'] = "enabled"
            cfg.seek(0)
            dump(data, cfg, indent=2)

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - uses: actions/checkout@v2

    - name: Update manifests
      run: ./run.sh -m


  Action-All:
    needs: Manifests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ./action


  Action-ARM:
    needs: Manifests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ./action
      with:
        targets: arm aarch64


  Test:
    needs: Manifests
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test:
          - ""
          - f
          - F
          - c
          - C
          - v
          - V
          - i
          - I
          - d
          - D
          - r
          - R
          - s
          - n
          #- h
          #- H
    name: 'T: ${{ matrix.test }}'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: test
      run: ./test.sh
      env:
        QUS_JOB: ${{ matrix.test }}
