name: 'push'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

jobs:


  debian:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        arch: [ x86_64, i686, aarch64, ppc64le, s390x, armhf, armel, mipsel, mips64el ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: BUILD=debian ./run.sh -b
      env:
        BASE_ARCH: ${{ matrix.arch }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/qus'
      run: docker push aptman/qus


  fedora:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        arch: [ x86_64, i686, aarch64, ppc64le, s390x, armv7hl ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: sudo apt-get install -y rpm2cpio zstd cpio curl

    - run: BUILD=fedora ./run.sh -b
      env:
        BASE_ARCH: ${{ matrix.arch }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'dbhi/qus'
      run: docker push aptman/qus


  manifests:
    if: github.event_name != 'pull_request' && github.repository == 'dbhi/qus'
    needs: [ debian, fedora ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Update manifests
      run: ./run.sh -m


  test:
    needs: [ manifests ]
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test: [ "", f, F, c, C, v, V, i, I, d, D, r, R, s, n ]
#, h, H
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: test
      run: ./test.sh
      env:
        QUS_JOB: ${{ matrix.test }}
